name: CI/CD Pipeline Trigger

on:
  push:
    branches:
      - development
      - release
      - main
  workflow_dispatch:
permissions:
  security-events: write
  contents: read


jobs:
  call-wrapper:
    uses: reddeppa427/ci-template/.github/workflows/ci-java-template.yml@main
    with:
      java-version: '11'
      deploy-env: ${{ github.ref_name == 'main' && 'Production' || github.ref_name == 'release' && 'QA' || 'Dev' }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
