name: MyJavaApp

on:
  workflow_dispatch:

permissions:
  security-events: write
  contents: read

jobs:
  build:
    uses: reddeppa-org/ci-template/.github/workflows/java_build_reusable_template.yml@main
    with:
      use_maven: true           # or false, as needed
      use_gradle: false         # or true, as needed
      java_version: '17'        # or any version you want
      java_distribution: 'temurin' # or 'zulu', 'adopt', etc.
      application_name: 'my-java-app'
      branch: 'development'            # or any branch you want to build
      runner: 'windows-latest'  # or 'ubuntu-latest', etc.
      environment: 'dev'           # or set to your environment name if needed
      run_tests: false        # or set to your environment name if needed      
      custom_script: 'echo Hello from wrapper! Build Completed Successfully Verify the Artifacts'

  
  security-gate:
    uses: reddeppa-org/ci-template/.github/workflows/gate-security.yml@main
    with:
      repo_owner: "${{ github.repository_owner }}"
      repo_name: "${{ github.repository }}"
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
  
  
  # deploy:
  #   uses: reddeppa-org/ci-template/.github/workflows/java_release_reusable_template.yml@main
  #   with:
  #     app_name: myapp                # Replace with your application name
  #     war_path: ./target/myapp.war   # Replace with the path to your WAR file
  #     remote_host: ${{ secrets.REMOTE_HOST }}         # Store in GitHub secrets
  #     remote_user: ${{ secrets.REMOTE_USER }}         # Store in GitHub secrets
  #     remote_password: ${{ secrets.REMOTE_PASSWORD }} # Store in GitHub secrets
